---
title: "Ecoli"
output:
  html_document:
    df_print: paged
vignette: |
  %\VignetteIndexEntry{Ecoli} %\VignetteEngine{knitr::rmarkdown}
---

```{r "setup", include=FALSE}
knitr::opts_knit$set(root.dir = "../")  # with something else than `getwd()`
library(RHermes)
require(enviPat)
library(igraph)
require(mzR)
require(magrittr)
require(CHNOSZ)
require(ggplot2)
require(viridis)
require(tidyverse)
library(gtools)
library(data.table)
library(keras)
library(BiocParallel)
library(plotly)
```

```{r warning=FALSE}
# setwd("../") #For unknitted use of the chunk
myHermes <- RHermesExp()
myHermes <- setExpParam(myHermes,
                        params = ExpParam(ppm = 3, res = 120000,
                                          instr = "Orbitrap", minmz = 50,
                                          maxmz = 1200))
negHermes <- RHermesExp()
negHermes <- setExpParam(negHermes,
                         params = ExpParam(ppm = 3, res = 120000,
                                          instr = "Orbitrap", minmz = 50,
                                          maxmz = 1200, ion = "-"))
```


```{r}
myHermes <- setDB(myHermes, "custom", filename = "D:/merge_KEGG_ECMDB.csv") 
myHermes <- remAd(myHermes, myHermes@metadata@ExpParam@adlist$adduct[-c(1:5)])

negHermes <- setDB(negHermes, "custom", filename = "D:/merge_KEGG_ECMDB.csv")
negHermes <- remAd(negHermes, negHermes@metadata@ExpParam@adlist$adduct[-c(1,7)])

```



```{r, message = 1, warning = FALSE}
dir <- "D:/Ecoli_GaryMichi/20201109_MSH_ID-X_pHILIC_E-coli_MS1_Yanes-Lab/MS1_positive/"
fil <- list.files(dir, pattern = ".*pos.*.mzML", full.names = TRUE)[c(6,9)] #Blank and Sample
myHermes <- processMS1(myHermes, files = fil)


dir <- "D:/Ecoli_GaryMichi/20201109_MSH_ID-X_pHILIC_E-coli_MS1_Yanes-Lab/MS1_negative/"
fil <- list.files(dir, pattern = ".*neg.*.mzML", full.names = TRUE)[c(6,9)]
negHermes <- processMS1(negHermes, files = fil)

```

```{r, message = FALSE, warning=FALSE}
s <- getSOIpar("double")
myHermes <- findSOI(myHermes, params = s, fileID = c(1,2,2,2,2),
                      against = c(0,0,1,1,1))
myHermes <- cleanSOI(myHermes, soiid = 4, minint = 10000, FALSE)
myHermes <- cleanSOI(myHermes, soiid = 5, minint = 10000, TRUE)
myHermes <- removeISF(myHermes, id = 4)
myHermes <- removeISF(myHermes, id = 5)
saveRDS(myHermes, file = "D:/HermesResults/Ecoli/PosSOIFilter.rds")


negHermes <- findSOI(negHermes, params = s, fileID = c(1,2,2,2,2),
                      against = c(0,0,1,1,1))
negHermes <- cleanSOI(negHermes, soiid = 4, 10000, FALSE)
negHermes <- cleanSOI(negHermes, soiid = 5, 10000, TRUE)
negHermes <- removeISF(negHermes, id = 4)
negHermes <- removeISF(negHermes, id = 5)

saveRDS(negHermes, file = "D:/HermesResults/Ecoli/NegSOIFilter.rds")

```


```{r}
myHermes <- generateIL(myHermes, id = 4, par = ILParam(priorization = "yes", ad = c("M+H", "M+NH4", "M+CH3OH+H")))
# exportIL(myHermes, 1, maxOver = 15, sepFiles = TRUE)

negHermes <- generateIL(negHermes, id = 4, par = ILParam(priorization = "yes", ad = c("M-H")))
# exportIL(negHermes, 1, maxOver = 15, sepFiles = TRUE)

```

```{r}
ms2f <- list.files("D:/Ecoli_GaryMichi/tMS2_positive/", pattern = ".*pos.*.mzML", full.names = TRUE)
myHermes <- processMS2(myHermes, 1, MS2files = ms2f, useDB = TRUE, 
                    referenceDB = "D:/MS2ID_B2R_20201113_083214.rds",
                    sstype = "regular", mincos = 0.1)
saveRDS(myHermes, file = "D:/HermesResults/Ecoli/PosResults.rds")


ms2f <- list.files("D:/Ecoli_GaryMichi/tMS2_negative/", pattern = ".*neg.*.mzML", full.names = TRUE)
negHermes <- processMS2(negHermes, 1, MS2files = ms2f, useDB = TRUE,
                     referenceDB = "D:/MS2ID_B2R_20201113_083214.rds",
                     sstype = "regular", mincos = 0.1)
saveRDS(negHermes, file = "D:/HermesResults/Ecoli/NegResults.rds")

```

<!--  ```{r} -->
<!--  IL <- myHermes@data@MS2Exp[[1]]@IL -->

<!--  refined_entries <- c(1378, 1679, 2006, 2044, 2068, 2040, 428, 965, 1301, 1266, 446, 1021, 879, 1469, 1556, 1655, 487,551, 1629, 501, 582, 1908, 1456, 1309, 730, 1760, 1832, 1599, 1645, 1540, 1792, 227, 487, 551, 1371, 1540, 1608, 1141, 1348, 469, 564, 2046, 1375, 1491, 1435, 1953, 1268, 2087, 1339, 1929, 210, 2109) -->

<!--  any(duplicated(refined_entries)) -->

<!--  curatedIL <- IL@IL[unique(refined_entries), ] -->

<!--  lowintIL <- curatedIL[curatedIL$MaxInt < 100000,] -->

<!-- ``` -->



<!-- ## 3 m/z range analysis -->
<!-- ```{r warning=FALSE} -->
<!-- # setwd("../") #For unknitted use of the chunk -->
<!-- myHermes <- RHermesExp() -->
<!-- myHermes <- setExpParam(myHermes, -->
<!--                         params = ExpParam(ppm = 3, res = 120000, -->
<!--                                           instr = "Orbitrap", minmz = 50, -->
<!--                                           maxmz = 1200)) -->

<!-- negHermes <- RHermesExp() -->
<!-- negHermes <- setExpParam(negHermes, -->
<!--                          params = ExpParam(ppm = 3, res = 120000, -->
<!--                                           instr = "Orbitrap", minmz = 50, -->
<!--                                           maxmz = 1200, ion = "-")) -->

<!-- ``` -->


<!-- ```{r} -->
<!-- myHermes <- setDB(myHermes, "custom", filename = "D:/merge_KEGG_ECMDB.csv") -->
<!-- myHermes <- remAd(myHermes, c("M+IsoProp+H", "M+IsoProp+Na+H", "M+DMSO+H")) -->

<!-- negHermes <- setDB(negHermes, "custom", filename = "D:/merge_KEGG_ECMDB.csv") -->
<!-- negHermes <- remAd(negHermes, c("M+IsoProp+H", "M+IsoProp+Na+H", "M+DMSO+H")) -->

<!-- ``` -->



<!-- ```{r, message = 1, warning = FALSE} -->
<!-- dir <- "D:/Ecoli_GaryMichi/20201109_MSH_ID-X_pHILIC_E-coli_MS1_Yanes-Lab/MS1_positive/" -->
<!-- fil <- list.files(dir, pattern = ".*pos.*.mzML", full.names = TRUE)[5:10] -->
<!-- myHermes <- processMS1(myHermes, files = fil) -->
<!-- saveRDS(myHermes, file ="D:/Ecoli_GaryMichi/Ranges_MS1_pos_PL.rds") -->


<!-- dir <- "D:/Ecoli_GaryMichi/20201109_MSH_ID-X_pHILIC_E-coli_MS1_Yanes-Lab/MS1_negative/" -->
<!-- fil <- list.files(dir, pattern = ".*neg.*.mzML", full.names = TRUE)[5:10] -->
<!-- negHermes <- processMS1(negHermes, files = fil) -->
<!-- saveRDS(negHermes, file ="D:/Ecoli_GaryMichi/Ranges_MS1_neg_PL.rds") -->

<!-- ``` -->

<!-- ```{r, message = FALSE, warning=FALSE} -->
<!-- s <- getSOIpar("double") -->
<!-- myHermes <- findSOI(myHermes, params = s, fileID = c(1,2,3,4,5,6,3,5,5), -->
<!--                       against = c(0,0,0,0,0,0,5,3,6)) -->
<!-- saveRDS(myHermes, file = "D:/Ecoli_GaryMichi/Ranges_MS1_pos_SOI_filter.rds") -->


<!-- negHermes <- findSOI(negHermes, params = s, fileID = c(1,2,3,4,5,6,3,5,5), -->
<!--                       against = c(0,0,0,0,0,0,5,3,6)) -->
<!-- saveRDS(negHermes, file = "D:/Ecoli_GaryMichi/Ranges_MS1_neg_SOI_filter.rds") -->

<!-- ``` -->

## Low intensity High IT study

```{r}
myHermes <- processMS2(myHermes, 1, MS2files = "D:/Ecoli_GaryMichi/Curated_lowint/Curated_lowint/UNL_Ecoli_low-int_pos.mzML",
                    useDB = TRUE, mincos = 0.1, referenceDB = "D:/MS2ID_B2R_20201113_083214.rds", sstype = "1scan")

myHermes@data@MS2Exp[[2]] <- myHermes@data@MS2Exp[[1]] 
myHermes <- processMS2(myHermes, 2, MS2files = "D:/Ecoli_GaryMichi/Curated_lowint/Curated_lowint/UNL_Ecoli_low-int_HCD50_pos.mzML",
                    useDB = TRUE, mincos = 0.1, referenceDB = "D:/MS2ID_B2R_20201113_083214.rds")
saveRDS(myHermes, "D:/HermesResults/Ecoli/Lowint.rds")
```

## Labelled samples study

```{r}
myHermes <- RHermesExp()
myHermes <- setExpParam(myHermes,
                        params = ExpParam(ppm = 3, res = 120000,
                                          instr = "Orbitrap", minmz = 50,
                                          maxmz = 1200))
negHermes <- RHermesExp()
negHermes <- setExpParam(negHermes,
                         params = ExpParam(ppm = 3, res = 120000,
                                          instr = "Orbitrap", minmz = 50,
                                          maxmz = 1200, ion = "-"))
```


```{r}
myHermes <- setDB(myHermes, "custom", filename = "D:/merge_KEGG_ECMDB.csv") 
myHermes <- remAd(myHermes, myHermes@metadata@ExpParam@adlist$adduct[-c(1:5)])
negHermes <- setDB(negHermes, "custom", filename = "D:/merge_KEGG_ECMDB.csv")
negHermes <- remAd(negHermes, negHermes@metadata@ExpParam@adlist$adduct[-c(1,7)])

```


```{r, message = 1, warning = FALSE}
dir <- "D:/Ecoli_GaryMichi/20201109_MSH_ID-X_pHILIC_E-coli_MS1_Yanes-Lab/MS1_positive/"
fil <- list.files(dir, pattern = ".*pos.*.mzML", full.names = TRUE)[c(6,3)] #Blank and Sample
myHermes <- processMS1(myHermes, files = fil, labelled = TRUE)

dir <- "D:/Ecoli_GaryMichi/20201109_MSH_ID-X_pHILIC_E-coli_MS1_Yanes-Lab/MS1_negative/"
fil <- list.files(dir, pattern = ".*neg.*.mzML", full.names = TRUE)[c(6,3)]
negHermes <- processMS1(negHermes, files = fil, labelled = TRUE)

```

```{r, message = FALSE, warning=FALSE}
unlabPos <- readRDS("D:/HermesResults/Ecoli/PosResults.rds")
myHermes@data@SOI <- unlabPos@data@SOI
myHermes@data@SOI[[1]]@filename <- myHermes@metadata@filenames[1]
myHermes@data@SOI[[2]]@filename <- myHermes@metadata@filenames[2]
myHermes@data@SOI[[3]]@filename <- myHermes@metadata@filenames[2]
myHermes@data@SOI[[4]]@filename <- myHermes@metadata@filenames[2]
myHermes@data@SOI[[5]]@filename <- myHermes@metadata@filenames[2]
saveRDS(myHermes, file ="D:/HermesResults/Ecoli/Pos13CSOI.rds")


unlabNeg <- readRDS("D:/HermesResults/Ecoli/NegResults.rds")
negHermes@data@SOI <- unlabNeg@data@SOI
negHermes@data@SOI[[1]]@filename <- negHermes@metadata@filenames[1]
negHermes@data@SOI[[2]]@filename <- negHermes@metadata@filenames[2]
negHermes@data@SOI[[3]]@filename <- negHermes@metadata@filenames[2]
negHermes@data@SOI[[4]]@filename <- negHermes@metadata@filenames[2]
negHermes@data@SOI[[5]]@filename <- negHermes@metadata@filenames[2]
saveRDS(negHermes, file ="D:/HermesResults/Ecoli/Neg13CSOI.rds")
```

```{r}
sink("D:/HermesResults/Ecoli/sessionInfo.txt")
sessionInfo()
paste("Date: ", date())
sink()
```




